---
- name: Start terraform action
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: Clone terraform azure repo
      ansible.builtin.git:
        repo: "https://github.com/jskorzyn/terraform-azure.git"
        dest: /tmp

    - name: start tf file
      cloud.terraform.terraform:
        project_path: /tmp/terraform-azure
        state: present
        force_init: true