---
- name: Start terraform action
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: Create Terraform project 
      ansible.builtin.file:
        path: /tmp/git
        state: directory
        mode: '755'     

    - name: Clone terraform azure repo
      ansible.builtin.git:
        repo: "https://github.com/jskorzyn/terraform-azure.git"
        dest: /tmp/git

    - name: Initialize Terraform Provider
      cloud.terraform.terraform:
        project_path: /tmp/git
        state: absent
        force_init: true

    - name: Deploy Azure Instance with Terraform Provider
      cloud.terraform.terraform:
        project_path: /tmp/git
        state: present

    - name: check folder structure
      shell: ls -al /tmp/git
      register: folders

    - name: debug folders
      debug:
        var: folders.stdout

    - name: GIT Actions
      ansible.builtin.include_tasks:
        - "{{  playbook_dir }}/git_actions/git-tasks.yml"